// prisma/seeders/MalagaRegions.seeder.ts
import { PrismaClient } from "@prisma/client/extension"

export const seedMalagaRegions = async (prisma: PrismaClient) => {
  await prisma.malagaRegion.createMany({
    data:
      [
        { id: 1, name: "Antequera" },
        { id: 2, name: "Axarquía" },
        { id: 3, name: "Costa del Sol Occidental" },
        { id: 4, name: "Guadalteba" },
        { id: 5, name: "Málaga - Costa del Sol" },
        { id: 6, name: "Nororma" },
        { id: 7, name: "Serranía de Ronda" },
        { id: 8, name: "Sierra de las Nieves" },
        { id: 9, name: "Valle del Guadalhorce" }
      ],
    skipDuplicates: true,
  })

  await prisma.malagaCity.createMany({
    data: [
      { name: "Alameda", regionId: 1 },
      { name: "Alcaucín", regionId: 2 },
      { name: "Alfarnate", regionId: 2 },
      { name: "Alfarnatejo", regionId: 2 },
      { name: "Algarrobo", regionId: 2 },
      { name: "Algatocín", regionId: 7 },
      { name: "Alhaurín de la Torre", regionId: 9 },
      { name: "Alhaurín el Grande", regionId: 9 },
      { name: "Almáchar", regionId: 2 },
      { name: "Almargen", regionId: 4 },
      { name: "Almogía", regionId: 5 },
      { name: "Álora", regionId: 9 },
      { name: "Alpandeire", regionId: 7 },
      { name: "Antequera", regionId: 1 },
      { name: "Árchez", regionId: 2 },
      { name: "Archidona", regionId: 6 },
      { name: "Ardales", regionId: 4 },
      { name: "Arenas", regionId: 2 },
      { name: "Arriate", regionId: 7 },
      { name: "Atajate", regionId: 7 },
      { name: "Benadalid", regionId: 7 },
      { name: "Benahavís", regionId: 3 },
      { name: "Benalauría", regionId: 7 },
      { name: "Benalmádena", regionId: 3 },
      { name: "Benamargosa", regionId: 2 },
      { name: "Benamocarra", regionId: 2 },
      { name: "Benaoján", regionId: 7 },
      { name: "Benarrabá", regionId: 7 },
      { name: "Campillos", regionId: 4 },
      { name: "Canillas de Aceituno", regionId: 2 },
      { name: "Canillas de Albaida", regionId: 2 },
      { name: "Cañete la Real", regionId: 4 },
      { name: "Carratraca", regionId: 4 },
      { name: "Cartajima", regionId: 7 },
      { name: "Cártama", regionId: 9 },
      { name: "Casabermeja", regionId: 1 },
      { name: "Casarabonela", regionId: 8 },
      { name: "Casares", regionId: 3 },
      { name: "Coín", regionId: 9 },
      { name: "Colmenar", regionId: 2 },
      { name: "Comares", regionId: 2 },
      { name: "Cómpeta", regionId: 2 },
      { name: "Cortes de la Frontera", regionId: 7 },
      { name: "Cuevas Bajas", regionId: 6 },
      { name: "Cuevas de San Marcos", regionId: 6 },
      { name: "Cuevas del Becerro", regionId: 4 },
      { name: "Cútar", regionId: 2 },
      { name: "El Borge", regionId: 2 },
      { name: "El Burgo", regionId: 8 },
      { name: "Estepona", regionId: 3 },
      { name: "Faraján", regionId: 7 },
      { name: "Frigiliana", regionId: 2 },
      { name: "Fuengirola", regionId: 3 },
      { name: "Fuente de Piedra", regionId: 1 },
      { name: "Gaucín", regionId: 7 },
      { name: "Genalguacil", regionId: 7 },
      { name: "Guaro", regionId: 8 },
      { name: "Humilladero", regionId: 1 },
      { name: "Igualeja", regionId: 7 },
      { name: "Istán", regionId: 8 },
      { name: "Iznate", regionId: 2 },
      { name: "Jimera de Líbar", regionId: 7 },
      { name: "Jubrique", regionId: 7 },
      { name: "Júzcar", regionId: 7 },
      { name: "Macharaviaya", regionId: 2 },
      { name: "Málaga", regionId: 5 },
      { name: "Manilva", regionId: 3 },
      { name: "Marbella", regionId: 3 },
      { name: "Mijas", regionId: 3 },
      { name: "Moclinejo", regionId: 2 },
      { name: "Mollina", regionId: 1 },
      { name: "Monda", regionId: 8 },
      { name: "Montejaque", regionId: 7 },
      { name: "Nerja", regionId: 2 },
      { name: "Ojén", regionId: 8 },
      { name: "Parauta", regionId: 7 },
      { name: "Periana", regionId: 2 },
      { name: "Pizarra", regionId: 9 },
      { name: "Pujerra", regionId: 7 },
      { name: "Rincón de la Victoria", regionId: 2 },
      { name: "Riogordo", regionId: 2 },
      { name: "Ronda", regionId: 7 },
      { name: "Salares", regionId: 2 },
      { name: "Sayalonga", regionId: 2 },
      { name: "Sedella", regionId: 2 },
      { name: "Sierra de Yeguas", regionId: 4 },
      { name: "Teba", regionId: 4 },
      { name: "Tolox", regionId: 8 },
      { name: "Torremolinos", regionId: 3 },
      { name: "Torrox", regionId: 2 },
      { name: "Totalán", regionId: 2 },
      { name: "Valle de Abdalajís", regionId: 9 },
      { name: "Vélez-Málaga", regionId: 2 },
      { name: "Villanueva de Algaidas", regionId: 6 },
      { name: "Villanueva de la Concepción", regionId: 1 },
      { name: "Villanueva de Tapia", regionId: 6 },
      { name: "Villanueva del Rosario", regionId: 6 },
      { name: "Villanueva del Trabuco", regionId: 6 },
      { name: "Viñuela", regionId: 2 },
      { name: "Yunquera", regionId: 8 },
      { name: "Montecorto", regionId: 7 },
      { name: "Serrato", regionId: 7 }
    ],
    skipDuplicates: true
  })
}