const Usercreated = {
  backup_code_enabled: false,
  banned: false,
  bypass_client_trust: false,
  create_organization_enabled: true,
  created_at: 1774369635888,
  delete_self_enabled: true,
  email_addresses: [
    {
      created_at: 1774369635891,
      email_address: 'javtorres.devtest@gmail.com',
      id: 'idn_3BOomOBCKihtlEBfkaka0sZM6im',
      linked_to: [],
      matches_sso_connection: false,
      object: 'email_address',
      reserved: false,
      updated_at: 1774369635891,
      verification: [Object]
    }
  ],
  enterprise_accounts: [],
  external_accounts: [],
  external_id: null,
  first_name: 'Javier',
  has_image: false,
  id: 'user_3BOomMmY3xnRWFIJT3nObjv27ok',
  image_url: 'https://img.clerk.com/eyJ0eXBlIjoiZGVmYXVsdCIsImlpZCI6Imluc18zOEJjVEpuR001TGNJTWw0d2VHSzhXVjRnYmIiLCJyaWQiOiJ1c2VyXzNCT29tTW1ZM3huUldGSUpUM25PYmp2MjdvayIsImluaXRpYWxzIjoiSlAifQ',    
  last_active_at: null,
  last_name: 'Perez',
  last_sign_in_at: null,
  legal_accepted_at: null,
  locale: null,
  locked: false,
  lockout_expires_in_seconds: null,
  mfa_disabled_at: null,
  mfa_enabled_at: null,
  object: 'user',
  passkeys: [],
  password_enabled: true,
  password_last_updated_at: 1774369635888,
  phone_numbers: [],
  primary_email_address_id: 'idn_3BOomOBCKihtlEBfkaka0sZM6im',
  primary_phone_number_id: null,
  primary_web3_wallet_id: null,
  private_metadata: {},
  profile_image_url: 'https://www.gravatar.com/avatar?d=mp',
  public_metadata: {},
  requires_password_reset: false,
  saml_accounts: [],
  totp_enabled: false,
  two_factor_enabled: false,
  unsafe_metadata: {},
  updated_at: 1774369635895,
  username: null,
  verification_attempts_remaining: 100,
  web3_wallets: []
}









const Usercreated2 = {
  backup_code_enabled: false,
  banned: false,
  bypass_client_trust: false,
  create_organization_enabled: true,
  created_at: 1774369774666,
  delete_self_enabled: true,
  email_addresses: [
    {
      created_at: 1774369774632,
      email_address: 'fleivormx@gmail.com',
      id: 'idn_3BOp3tNo6hoV5ThwRf0PcdOGwsP',
      linked_to: [Array],
      matches_sso_connection: false,
      object: 'email_address',
      reserved: false,
      updated_at: 1774369774676,
      verification: [Object]
    }
  ],
  enterprise_accounts: [],
  external_accounts: [
    {
      approved_scopes: 'email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile',
      avatar_url: 'https://lh3.googleusercontent.com/a/ACg8ocKyk7QSKdpPK1O29SriIcsYM8sKCUoEX1Oz4BtCCrOmjSlyLYg=s1000-c',
      created_at: 1774369774625,
      email_address: 'fleivormx@gmail.com',
      email_address_verified: true,
      external_account_id: 'eac_3BOp3pmClXpCCJmSARGX6EasYGT',
      family_name: 'MX',
      first_name: 'Fleivor',
      given_name: 'Fleivor',
      google_id: '111278924024600265885',
      id: 'idn_3BOp3t2cVwGWbTx3HCPsPp6dfUi',
      identification_id: 'idn_3BOp3t2cVwGWbTx3HCPsPp6dfUi',
      image_url: 'https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLeWs3UVNLZHBQSzFPMjlTcmlJY3NZTThzS0NVb0VYMU96NEJ0Q0NyT21qU2x5TFlnPXMxMDAwLWMiLCJzIjoiNnB1RVcxUG9ZRnVPZzRjZlBuRVFSM2pEc2Rtemh0UWpXekRYakdZSXJ3USJ9',
      label: null,
      last_name: 'MX',
      object: 'google_account',
      picture: 'https://lh3.googleusercontent.com/a/ACg8ocKyk7QSKdpPK1O29SriIcsYM8sKCUoEX1Oz4BtCCrOmjSlyLYg=s1000-c',
      provider: 'oauth_google',
      provider_user_id: '111278924024600265885',
      public_metadata: {},
      updated_at: 1774369774625,
      username: null,
      verification: [Object]
    }
  ],
  external_id: null,
  first_name: 'Fleivor',
  has_image: true,
  id: 'user_3BOp3vskwsRC02CztdPzZbl74iH',
  image_url: 'https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zQk9wM3ZwR082QklBeXpIS2htNm4wb2tsNzMifQ',
  last_active_at: 1774369774664,
  last_name: 'MX',
  last_sign_in_at: null,
  legal_accepted_at: null,
  locale: null,
  locked: false,
  lockout_expires_in_seconds: null,
  mfa_disabled_at: null,
  mfa_enabled_at: null,
  object: 'user',
  passkeys: [],
  password_enabled: false,
  password_last_updated_at: null,
  phone_numbers: [],
  primary_email_address_id: 'idn_3BOp3tNo6hoV5ThwRf0PcdOGwsP',
  primary_phone_number_id: null,
  primary_web3_wallet_id: null,
  private_metadata: {},
  profile_image_url: 'https://images.clerk.dev/oauth_google/img_3BOp3vpGO6BIAyzHKhm6n0okl73',     
  public_metadata: {},
  requires_password_reset: false,
  saml_accounts: [],
  totp_enabled: false,
  two_factor_enabled: false,
  unsafe_metadata: {},
  updated_at: 1774369774697,
  username: null,
  verification_attempts_remaining: 100,
  web3_wallets: []
}